spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: q1w2e3R$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: your_jwt_secret_key_here_it_should_be_at_least_256_bits_long
  expiration: 86400000  # 24?? (??? ??)

server:
  port: 8080