spring:
  data:
    mongodb:
      uri: mongodb://admana:000000@218.55.78.63:37018/togeter?authSource=admin

jwt:
  secret: your_jwt_secret_key_here_it_should_be_at_least_256_bits_long
  expiration: 86400000  # 24?? (??? ??)

server:
  port: 8080


collection:
  product_collection: TB_PRODUCT_COLLECTION
  member_collection: TB_MEMBER_COLLECTION
  board_collection: TB_BOARD_COLLECTION